import { readFile, readdir, writeFile } from 'node:fs/promises'
import { join } from 'node:path'
import { createHash } from 'node:crypto'
const lock = JSON.parse(await readFile('package-lock.json', 'utf8')),
	groups = new Map(),
	rows = []
for (const [path, entry] of Object.entries(lock.packages)) {
	if (!path || entry.dev) continue
	let pkg
	try {
		pkg = JSON.parse(await readFile(join(path, 'package.json'), 'utf8'))
	} catch {
		continue
	}
	const name = pkg.name + '@' + pkg.version,
		license = pkg.license ?? 'See package license',
		texts = []
	for (const file of await readdir(path))
		if (/^(licen[sc]e|copying|notice)(\.[a-z0-9-]+)?$/i.test(file))
			try {
				texts.push(await readFile(join(path, file), 'utf8'))
			} catch {}
	const text = (texts.join('\n\n') || `License: ${license}. Distributed source and license: ${entry.resolved}`)
		.replaceAll('\r\n', '\n')
		.replace(/[ \t]+$/gm, '')
		.trim()
	const hash = createHash('sha256').update(text).digest('hex').slice(0, 16)
	if (!groups.has(hash)) groups.set(hash, { names: [], text })
	groups.get(hash).names.push(name)
	rows.push(
		`| ${name} | ${typeof license === 'string' ? license : JSON.stringify(license)} | [Source package](${entry.resolved}) |`
	)
}
await writeFile(
	'docs/third-party-notices.md',
	'# Runtime dependency notices\n\nGenerated by `node scripts/dependency-notices.mjs` from the installed lockfile. Runtime packages are unmodified. Hyena source is Apache-2.0; dependency licenses remain applicable. The linked source tarballs include the original package sources, including Mediabunny under MPL-2.0.\n\n| Package | License | Source |\n|---|---|---|\n' +
		rows.join('\n') +
		'\n\n' +
		[...groups.values()]
			.map((g) => '## ' + g.names.join(', ') + '\n\n```text\n' + g.text.replaceAll('```', '~~~') + '\n```\n')
			.join('\n')
)
console.log(`Recorded ${rows.length} runtime packages and ${groups.size} distinct notice texts`)
